export type ThrillLevel = 1 | 2 | 3 | 4 | 5;
export type BestTime = "morning" | "afternoon" | "evening" | "anytime";
export type WaitTendency = "high" | "medium" | "low";

export interface AttractionInfo {
  id: number;
  nameJa: string;
  nameEn: string;
  area: string;
  areaEn: string;
  heightMin: number | null; // cm、なければ null
  thrillLevel: ThrillLevel;
  isDPA: boolean;
  bestTime: BestTime;
  waitTendency: WaitTendency;
  descJa: string;
  descEn: string;
}

// ──────────────────────────────────────────────────────────
// TDL アトラクション
// ──────────────────────────────────────────────────────────
export const TDL_ATTRACTIONS: AttractionInfo[] = [
  {
    id: 197,
    nameJa: "美女と野獣・魔法のものがたり",
    nameEn: "Beauty and the Beast: Magical Tale",
    area: "ニューファンタジーランド",
    areaEn: "New Fantasyland",
    heightMin: null,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "映画の世界に迷い込む没入型ライド。待ち時間が最も長くなりやすいため開園直後が狙い目。DPAの活用も有効。",
    descEn: "An immersive ride set inside Beast's enchanted castle. Waits run highest all day — ride first thing or use DPA.",
  },
  {
    id: 196,
    nameJa: "ベイマックスのハッピーライド",
    nameEn: "Baymax's Happy Ride",
    area: "トゥモローランド",
    areaEn: "Tomorrowland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "high",
    descJa: "ベイマックスと一緒にくるくる回る爽快ライド。家族全員が楽しめる。混雑時は待ち時間が長くなりがち。",
    descEn: "A spinning ride with Baymax. Fun for all ages. Waits can stack up — try midday when top-tier rides are busiest.",
  },
  {
    id: 174,
    nameJa: "プーさんのハニーハント",
    nameEn: "Pooh's Hunny Hunt",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ランダムな動きが特徴のユニークなライド。DPA対象のため、朝一かDPA確保を優先しよう。",
    descEn: "A unique trackless ride with unpredictable movements. DPA eligible — secure a pass or ride right at opening.",
  },
  {
    id: 164,
    nameJa: "ピーター・パン空の旅",
    nameEn: "Peter Pan's Flight",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "空を飛ぶような感覚で楽しめる定番アトラクション。長蛇の列になりやすいので開園直後に乗るのがベスト。",
    descEn: "Fly over Neverland in a classic dark ride. Lines build fast — aim for the first 30 minutes after opening.",
  },
  {
    id: 160,
    nameJa: "ビッグサンダー・マウンテン",
    nameEn: "Big Thunder Mountain",
    area: "ウエスタンランド",
    areaEn: "Westernland",
    heightMin: 102,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "evening",
    waitTendency: "medium",
    descJa: "鉱山列車で駆け抜けるスリル満点のジェットコースター。身長制限102cm。夕方は比較的空いてくることが多い。",
    descEn: "A classic mine train coaster through the wilderness. Height: 102cm+. Evening is often the sweet spot for shorter waits.",
  },
  {
    id: 171,
    nameJa: "ホーンテッドマンション",
    nameEn: "Haunted Mansion",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 2,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "medium",
    descJa: "999人の幽霊が住むお屋敷を巡るダークライド。怖さよりも楽しさが勝る人気アトラクション。",
    descEn: "Tour a haunted mansion with 999 grinning ghosts. More fun than scary — a must-do at any time of day.",
  },
  {
    id: 162,
    nameJa: "スプラッシュ・マウンテン",
    nameEn: "Splash Mountain",
    area: "クリッターカントリー",
    areaEn: "Critter Country",
    heightMin: 90,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "medium",
    descJa: "ログに乗って激流を下るウォーターライド。身長制限90cm。濡れることを覚悟しよう！",
    descEn: "A log flume ride with a thrilling final drop. Height: 90cm+. Expect to get wet — bring a poncho or spare clothes!",
  },
  {
    id: 189,
    nameJa: "モンスターズ・インク \"ライド＆ゴーシーク！\"",
    nameEn: "Monsters, Inc. Ride & Go Seek!",
    area: "トゥモローランド",
    areaEn: "Tomorrowland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "medium",
    descJa: "懐中電灯でモンスターを探しながら進む参加型アトラクション。子供から大人まで楽しめる。",
    descEn: "An interactive dark ride where you spot monsters with a flashlight. Great for families — manageable waits most of the day.",
  },
  {
    id: 183,
    nameJa: "スター・ツアーズ：ザ・アドベンチャーズ・コンティニュー",
    nameEn: "Star Tours: The Adventures Continue",
    area: "トゥモローランド",
    areaEn: "Tomorrowland",
    heightMin: 102,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "low",
    descJa: "スター・ウォーズの世界をシミュレーターで体験。ランダムシナリオで何度でも楽しめる。身長制限102cm。",
    descEn: "A Star Wars motion simulator with randomized scenarios. Height: 102cm+. Usually shorter waits — a hidden gem in the afternoon.",
  },
  {
    id: 167,
    nameJa: "ミッキーのフィルハーマジック",
    nameEn: "Mickey's PhilharMagic",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "4Dシアターでディズニー映画の名場面を体験。待ち時間が少なく、雨の日でも楽しめる穴場。",
    descEn: "A 4D theater featuring iconic Disney movie scenes. Low waits, climate-controlled, and a great rainy day option.",
  },
];

// ──────────────────────────────────────────────────────────
// TDS アトラクション
// ──────────────────────────────────────────────────────────
export const TDS_ATTRACTIONS: AttractionInfo[] = [
  {
    id: 219,
    nameJa: "ソアリン：ファンタスティック・フライト",
    nameEn: "Soaring: Fantastic Flight",
    area: "ポートディスカバリー",
    areaEn: "Port Discovery",
    heightMin: 102,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "大空を飛ぶ感覚を味わえる人気NO.1アトラクション。身長制限102cm。DPA必須レベルの人気を誇る。",
    descEn: "The most popular attraction at DisneySea — a breathtaking hang-gliding simulation. Height: 102cm+. DPA is highly recommended.",
  },
  {
    id: 255,
    nameJa: "アナとエルサのフローズンジャーニー",
    nameEn: "Anna & Elsa's Frozen Journey",
    area: "ファンタジースプリングス",
    areaEn: "Fantasy Springs",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "「アナと雪の女王」の世界を旅するボートライド。ファンタジースプリングス内で最も人気の高いアトラクション。",
    descEn: "A boat journey through the Frozen kingdom. The most sought-after ride in Fantasy Springs — DPA or early arrival essential.",
  },
  {
    id: 256,
    nameJa: "ラプンツェルのランタンフェスティバル",
    nameEn: "Rapunzel's Lantern Festival",
    area: "ファンタジースプリングス",
    areaEn: "Fantasy Springs",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ランタンが舞う幻想的な世界を巡るボートライド。ラプンツェルの世界観に浸れる新エリアの目玉。",
    descEn: "Drift through a glowing lantern-lit world inspired by Tangled. A Fantasy Springs highlight — DPA makes a big difference here.",
  },
  {
    id: 257,
    nameJa: "ピーター・パンのネバーランドアドベンチャー",
    nameEn: "Peter Pan's Neverland Adventure",
    area: "ファンタジースプリングス",
    areaEn: "Fantasy Springs",
    heightMin: null,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ネバーランドを空から冒険するライド。ファンタジースプリングスの3アトラクション中最もスリリング。",
    descEn: "Soar over Neverland in an adventure ride. The most thrilling of the three Fantasy Springs attractions.",
  },
  {
    id: 243,
    nameJa: "タワー・オブ・テラー",
    nameEn: "Tower of Terror",
    area: "アメリカンウォーターフロント",
    areaEn: "American Waterfront",
    heightMin: 102,
    thrillLevel: 5,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "13階から落下するシー最大のスリルライド。身長制限102cm。心臓の弱い方はご注意を。DPA対象。",
    descEn: "DisneySea's most intense ride — a 13-floor drop tower. Height: 102cm+. Not for the faint of heart. DPA available.",
  },
  {
    id: 222,
    nameJa: "インディ・ジョーンズ・アドベンチャー：クリスタルスカルの魔宮",
    nameEn: "Indiana Jones Adventure: Temple of the Crystal Skull",
    area: "ロストリバーデルタ",
    areaEn: "Lost River Delta",
    heightMin: 117,
    thrillLevel: 4,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ジープで遺跡を駆け抜けるスリル満点のライド。身長制限117cm。振動が激しいため腰に不安がある方は注意。",
    descEn: "Race through an ancient temple in a jeep. Height: 117cm+. Intense bumps — not ideal if you have back issues.",
  },
  {
    id: 223,
    nameJa: "センター・オブ・ジ・アース",
    nameEn: "Journey to the Center of the Earth",
    area: "ミステリアスアイランド",
    areaEn: "Mysterious Island",
    heightMin: 117,
    thrillLevel: 5,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "地底2万マイルの世界を巡るシー屈指の名作ライド。身長制限117cm。最後の急上昇が圧巻。",
    descEn: "Explore the earth's core in DisneySea's iconic thrill ride. Height: 117cm+. The final launch is unforgettable.",
  },
  {
    id: 218,
    nameJa: "トイ・ストーリー・マニア！",
    nameEn: "Toy Story Mania!",
    area: "アメリカンウォーターフロント",
    areaEn: "American Waterfront",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "afternoon",
    waitTendency: "high",
    descJa: "4Dシューティングゲーム感覚のライド。家族・友人と点数を競おう！DPA対象で待ち時間が長くなりやすい。",
    descEn: "A 4D shooting game ride — compete for the highest score! DPA eligible and popular with families.",
  },
  {
    id: 242,
    nameJa: "レイジングスピリッツ",
    nameEn: "Raging Spirits",
    area: "アラビアンコースト",
    areaEn: "Arabian Coast",
    heightMin: 117,
    thrillLevel: 5,
    isDPA: false,
    bestTime: "evening",
    waitTendency: "medium",
    descJa: "360度ループありの本格コースター。身長制限117cm。夕方に比較的空きやすく狙い目の時間帯。",
    descEn: "A full 360° loop coaster. Height: 117cm+. Waits tend to ease in the evening — worth targeting then.",
  },
  {
    id: 247,
    nameJa: "ニモ＆フレンズ・シーライダー",
    nameEn: "Nemo & Friends SeaRider",
    area: "ポートディスカバリー",
    areaEn: "Port Discovery",
    heightMin: null,
    thrillLevel: 2,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "low",
    descJa: "小型潜水艦で海の生き物たちと泳ぐ体験型ライド。待ち時間が少なめで、混雑時の穴場スポット。",
    descEn: "Shrink down and swim with Nemo and friends in a mini sub. One of DisneySea's shorter queues — a smart choice on busy days.",
  },
];

// ──────────────────────────────────────────────────────────
// USJ アトラクション
// ──────────────────────────────────────────────────────────
export const USJ_ATTRACTIONS: AttractionInfo[] = [
  {
    id: 12061,
    nameJa: "マリオカート〜クッパの挑戦状〜",
    nameEn: "Mario Kart: Koopa's Challenge™",
    area: "スーパー・ニンテンドー・ワールド",
    areaEn: "Super Nintendo World",
    heightMin: 107,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ARと実物が融合した体感型レースライド。待ち時間が最も長くなりやすく、開園直後かエクスプレス・パス確保が必須。身長107cm以上。",
    descEn: "An AR-powered racing ride inside Nintendo World. Consistently the longest waits in the park — ride at opening or secure an Express Pass. Height: 107cm+.",
  },
  {
    id: 14402,
    nameJa: "Mine-Cart Madness™",
    nameEn: "Mine-Cart Madness™",
    area: "スーパー・ニンテンドー・ワールド",
    areaEn: "Super Nintendo World",
    heightMin: 107,
    thrillLevel: 3,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ドンキーコングがテーマのジェットコースター。大きなジャンプが特徴。身長107cm以上。開園ダッシュ推奨。",
    descEn: "A Donkey Kong-themed coaster with exciting jumps. Height: 107cm+. Opening dash recommended.",
  },
  {
    id: 12071,
    nameJa: "ヨッシー・アドベンチャー",
    nameEn: "Yoshi's Adventure™",
    area: "スーパー・ニンテンドー・ワールド",
    areaEn: "Super Nintendo World",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "medium",
    descJa: "ヨッシーに乗って卵を集める爽やかなライド。身長制限なしで家族全員OK。エリア内の穴場アトラクション。",
    descEn: "Ride Yoshi and collect eggs on a gentle tour of Nintendo World. No height minimum — great for all ages. One of the area's shorter waits.",
  },
  {
    id: 12065,
    nameJa: "ハリー・ポッター・アンド・ザ・フォービドゥン・ジャーニー",
    nameEn: "Harry Potter and the Forbidden Journey™",
    area: "ウィザーディング・ワールド・オブ・ハリー・ポッター",
    areaEn: "The Wizarding World of Harry Potter™",
    heightMin: 122,
    thrillLevel: 3,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ホグワーツ城内を飛び回る没入型フライトライド。USJ屈指の人気で待ち時間が長い。身長122cm以上。",
    descEn: "A soaring flight through Hogwarts Castle. One of USJ's most popular rides with consistently long waits. Height: 122cm+.",
  },
  {
    id: 12073,
    nameJa: "フライト・オブ・ザ・ヒッポグリフ",
    nameEn: "Flight of the Hippogriff™",
    area: "ウィザーディング・ワールド・オブ・ハリー・ポッター",
    areaEn: "The Wizarding World of Harry Potter™",
    heightMin: 122,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "evening",
    waitTendency: "medium",
    descJa: "ヒッポグリフに乗った爽快なコースター。身長122cm以上。夕方に待ちが落ち着くことが多い。",
    descEn: "A classic coaster ride on a hippogriff. Height: 122cm+. Waits tend to ease in the evening.",
  },
  {
    id: 12072,
    nameJa: "フリーズ・レイ・スライダーズ",
    nameEn: "Freeze Ray Sliders™",
    area: "ウィザーディング・ワールド・オブ・ハリー・ポッター",
    areaEn: "The Wizarding World of Harry Potter™",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "low",
    descJa: "身長制限なしで楽しめる穴場アトラクション。ハリー・ポッターエリアでは比較的空いている。",
    descEn: "No height minimum — one of the shorter waits in the Harry Potter area. Good choice for families.",
  },
  {
    id: 7092,
    nameJa: "ザ・フライング・ダイナソー",
    nameEn: "The Flying Dinosaur™",
    area: "ジュラシック・パーク",
    areaEn: "Jurassic Park",
    heightMin: 132,
    thrillLevel: 5,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "プテラノドンにつかまれたまま飛ぶフライングコースター。日本最長級のスリル！身長132cm以上。",
    descEn: "Japan's longest flying coaster — dangling under a pteranodon. Extreme thrills. Height: 132cm+.",
  },
  {
    id: 12067,
    nameJa: "ジュラシック・パーク・ザ・ライド",
    nameEn: "Jurassic Park - The Ride™",
    area: "ジュラシック・パーク",
    areaEn: "Jurassic Park",
    heightMin: 107,
    thrillLevel: 4,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "medium",
    descJa: "恐竜から逃げながらウォータースライドで急降下する爽快ライド。濡れるので覚悟を！身長107cm以上。",
    descEn: "Escape from dinosaurs on a thrilling water ride with a huge drop. Expect to get soaked! Height: 107cm+.",
  },
  {
    id: 12068,
    nameJa: "ジョーズ",
    nameEn: "Jaws™",
    area: "ニューヨーク・エリア",
    areaEn: "New York Area",
    heightMin: null,
    thrillLevel: 2,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "low",
    descJa: "巨大サメに追われるボートツアー。スリルは控えめで家族でも楽しめる。待ち時間は比較的少ない。",
    descEn: "A boat tour with a great white shark. More suspense than thrill — kid-friendly and usually shorter waits.",
  },
  {
    id: 7077,
    nameJa: "ハリウッド・ドリーム・ザ・ライド",
    nameEn: "Hollywood Dream - The Ride™",
    area: "ハリウッドエリア",
    areaEn: "Hollywood Area",
    heightMin: 122,
    thrillLevel: 4,
    isDPA: true,
    bestTime: "evening",
    waitTendency: "high",
    descJa: "BGM付きの爽快コースター。好きな曲を選んで乗れるのが特徴。身長122cm以上。夕方は比較的空く。",
    descEn: "A coaster where you choose your own soundtrack. Height: 122cm+. Waits tend to ease in the evening.",
  },
  {
    id: 12070,
    nameJa: "ハリウッド・ドリーム・ザ・ライド〜バックドロップ〜",
    nameEn: "Hollywood Dream - The Ride: Backdrop",
    area: "ハリウッドエリア",
    areaEn: "Hollywood Area",
    heightMin: 122,
    thrillLevel: 4,
    isDPA: false,
    bestTime: "evening",
    waitTendency: "medium",
    descJa: "後ろ向きで走るハリウッド・ドリームの逆走バージョン。スリル倍増！身長122cm以上。",
    descEn: "Hollywood Dream in reverse — backwards coaster thrills. Height: 122cm+. Usually shorter waits than the forward version.",
  },
  {
    id: 12066,
    nameJa: "ミニオン・ハチャメチャ・ライド",
    nameEn: "Minion Mayhem™",
    area: "ミニオン・パーク",
    areaEn: "Minion Park",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "medium",
    descJa: "ミニオンに変身する体感型シミュレーター。身長制限なしで家族みんなで楽しめる。",
    descEn: "Transform into a Minion in this fun 3D simulator. No height minimum — enjoyable for all ages.",
  },
  {
    id: 14918,
    nameJa: "ミニオン・ハチャメチャ・ミッション〜大悪党への道〜",
    nameEn: "Minion Mayhem Mission: Rise of a Villain",
    area: "ミニオン・パーク",
    areaEn: "Minion Park",
    heightMin: null,
    thrillLevel: 2,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "medium",
    descJa: "ミニオンパークの新アトラクション。悪党訓練に参加するシミュレーター体験。身長制限なし。",
    descEn: "A new Minion Park attraction — join villain training in this simulator experience. No height minimum.",
  },
  {
    id: 12082,
    nameJa: "スペース・ファンタジー・ザ・ライド",
    nameEn: "Space Fantasy - The Ride™",
    area: "スペシャルイベント/その他",
    areaEn: "Special Event/Other",
    heightMin: 122,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "evening",
    waitTendency: "medium",
    descJa: "宇宙空間を飛び回る大人気コースター。身長122cm以上。夕方のほうが比較的空いてくる。",
    descEn: "A beloved space-themed spinning coaster. Height: 122cm+. Shorter waits typically in the evening.",
  },
  {
    id: 13005,
    nameJa: "名探偵コナン・ザ・ワールド",
    nameEn: "Detective Conan: The World",
    area: "スペシャルイベント/その他",
    areaEn: "Special Event/Other",
    heightMin: null,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "名探偵コナンのシミュレーター型アトラクション。期間限定で非常に人気が高い。",
    descEn: "A limited-time Detective Conan simulator attraction. Very popular — ride early or use Express Pass.",
  },
  {
    id: 7214,
    nameJa: "SING ON TOUR",
    nameEn: "Sing on Tour",
    area: "ハリウッドエリア",
    areaEn: "Hollywood Area",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "SINGのキャラクターたちと楽しむショー形式のアトラクション。待ち時間が少ない穴場。",
    descEn: "A show-style attraction featuring the Sing characters. Low waits — a good choice at any time of day.",
  },
  {
    id: 12075,
    nameJa: "ザ・フライング・スヌーピー",
    nameEn: "The Flying Snoopy™",
    area: "ユニバーサル・ワンダーランド",
    areaEn: "Universal Wonderland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "スヌーピーと一緒にふわふわ空を飛ぶ子ども向けライド。家族連れに人気。",
    descEn: "A gentle flying ride with Snoopy. Perfect for young children and families.",
  },
  {
    id: 7061,
    nameJa: "ビッグ・バードのビッグトップ・サーカス",
    nameEn: "Big Bird's Big-Top Circus",
    area: "ユニバーサル・ワンダーランド",
    areaEn: "Universal Wonderland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "セサミストリートのビッグ・バードと楽しむサーカスショー。小さな子どもでも安心。",
    descEn: "A Sesame Street circus show with Big Bird. Safe and fun for the youngest guests.",
  },
  {
    id: 7067,
    nameJa: "エルモのゴーゴー・スケートボード",
    nameEn: "Elmo's Go-Go Skateboard™",
    area: "ユニバーサル・ワンダーランド",
    areaEn: "Universal Wonderland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "エルモのスケートボードに乗る子ども向けアトラクション。ユニバーサル・ワンダーランドの定番。",
    descEn: "A kids' skateboard ride with Elmo. A staple of Universal Wonderland.",
  },
  {
    id: 12083,
    nameJa: "セサミストリート4-Dムービーマジック",
    nameEn: "Sesame Street 4-D Movie Magic™",
    area: "ユニバーサル・ワンダーランド",
    areaEn: "Universal Wonderland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "セサミストリートの仲間たちが活躍する4Dシアター。待ち時間が少なく雨の日にも最適。",
    descEn: "A 4D theater featuring the Sesame Street gang. Low waits and a great indoor option on rainy days.",
  },
  {
    id: 12084,
    nameJa: "シュレック4-Dアドベンチャー",
    nameEn: "Shrek 4-D Adventure™",
    area: "スペシャルイベント/その他",
    areaEn: "Special Event/Other",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "シュレックの世界を体験する4Dアドベンチャー。身長制限なしで家族みんなで楽しめる。",
    descEn: "A 4D adventure in the world of Shrek. No height minimum — fun for the whole family.",
  },
];
