export type ThrillLevel = 1 | 2 | 3 | 4 | 5;
export type BestTime = "morning" | "afternoon" | "evening" | "anytime";
export type WaitTendency = "high" | "medium" | "low";

export interface AttractionInfo {
  id: number;
  nameJa: string;
  nameEn: string;
  area: string;
  areaEn: string;
  heightMin: number | null; // cm、なければ null
  thrillLevel: ThrillLevel;
  isDPA: boolean;
  bestTime: BestTime;
  waitTendency: WaitTendency;
  descJa: string;
  descEn: string;
}

// ──────────────────────────────────────────────────────────
// TDL アトラクション
// ──────────────────────────────────────────────────────────
export const TDL_ATTRACTIONS: AttractionInfo[] = [
  {
    id: 197,
    nameJa: "美女と野獣・魔法のものがたり",
    nameEn: "Beauty and the Beast: Magical Tale",
    area: "ニューファンタジーランド",
    areaEn: "New Fantasyland",
    heightMin: null,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "映画の世界に迷い込む没入型ライド。待ち時間が最も長くなりやすいため開園直後が狙い目。DPAの活用も有効。",
    descEn: "An immersive ride set inside Beast's enchanted castle. Waits run highest all day — ride first thing or use DPA.",
  },
  {
    id: 196,
    nameJa: "ベイマックスのハッピーライド",
    nameEn: "Baymax's Happy Ride",
    area: "トゥモローランド",
    areaEn: "Tomorrowland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "high",
    descJa: "ベイマックスと一緒にくるくる回る爽快ライド。家族全員が楽しめる。混雑時は待ち時間が長くなりがち。",
    descEn: "A spinning ride with Baymax. Fun for all ages. Waits can stack up — try midday when top-tier rides are busiest.",
  },
  {
    id: 174,
    nameJa: "プーさんのハニーハント",
    nameEn: "Pooh's Hunny Hunt",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ランダムな動きが特徴のユニークなライド。DPA対象のため、朝一かDPA確保を優先しよう。",
    descEn: "A unique trackless ride with unpredictable movements. DPA eligible — secure a pass or ride right at opening.",
  },
  {
    id: 164,
    nameJa: "ピーター・パン空の旅",
    nameEn: "Peter Pan's Flight",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "空を飛ぶような感覚で楽しめる定番アトラクション。長蛇の列になりやすいので開園直後に乗るのがベスト。",
    descEn: "Fly over Neverland in a classic dark ride. Lines build fast — aim for the first 30 minutes after opening.",
  },
  {
    id: 160,
    nameJa: "ビッグサンダー・マウンテン",
    nameEn: "Big Thunder Mountain",
    area: "ウエスタンランド",
    areaEn: "Westernland",
    heightMin: 102,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "evening",
    waitTendency: "medium",
    descJa: "鉱山列車で駆け抜けるスリル満点のジェットコースター。身長制限102cm。夕方は比較的空いてくることが多い。",
    descEn: "A classic mine train coaster through the wilderness. Height: 102cm+. Evening is often the sweet spot for shorter waits.",
  },
  {
    id: 171,
    nameJa: "ホーンテッドマンション",
    nameEn: "Haunted Mansion",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 2,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "medium",
    descJa: "999人の幽霊が住むお屋敷を巡るダークライド。怖さよりも楽しさが勝る人気アトラクション。",
    descEn: "Tour a haunted mansion with 999 grinning ghosts. More fun than scary — a must-do at any time of day.",
  },
  {
    id: 162,
    nameJa: "スプラッシュ・マウンテン",
    nameEn: "Splash Mountain",
    area: "クリッターカントリー",
    areaEn: "Critter Country",
    heightMin: 90,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "medium",
    descJa: "ログに乗って激流を下るウォーターライド。身長制限90cm。濡れることを覚悟しよう！",
    descEn: "A log flume ride with a thrilling final drop. Height: 90cm+. Expect to get wet — bring a poncho or spare clothes!",
  },
  {
    id: 189,
    nameJa: "モンスターズ・インク \"ライド＆ゴーシーク！\"",
    nameEn: "Monsters, Inc. Ride & Go Seek!",
    area: "トゥモローランド",
    areaEn: "Tomorrowland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "medium",
    descJa: "懐中電灯でモンスターを探しながら進む参加型アトラクション。子供から大人まで楽しめる。",
    descEn: "An interactive dark ride where you spot monsters with a flashlight. Great for families — manageable waits most of the day.",
  },
  {
    id: 183,
    nameJa: "スター・ツアーズ：ザ・アドベンチャーズ・コンティニュー",
    nameEn: "Star Tours: The Adventures Continue",
    area: "トゥモローランド",
    areaEn: "Tomorrowland",
    heightMin: 102,
    thrillLevel: 3,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "low",
    descJa: "スター・ウォーズの世界をシミュレーターで体験。ランダムシナリオで何度でも楽しめる。身長制限102cm。",
    descEn: "A Star Wars motion simulator with randomized scenarios. Height: 102cm+. Usually shorter waits — a hidden gem in the afternoon.",
  },
  {
    id: 167,
    nameJa: "ミッキーのフィルハーマジック",
    nameEn: "Mickey's PhilharMagic",
    area: "ファンタジーランド",
    areaEn: "Fantasyland",
    heightMin: null,
    thrillLevel: 1,
    isDPA: false,
    bestTime: "anytime",
    waitTendency: "low",
    descJa: "4Dシアターでディズニー映画の名場面を体験。待ち時間が少なく、雨の日でも楽しめる穴場。",
    descEn: "A 4D theater featuring iconic Disney movie scenes. Low waits, climate-controlled, and a great rainy day option.",
  },
];

// ──────────────────────────────────────────────────────────
// TDS アトラクション
// ──────────────────────────────────────────────────────────
export const TDS_ATTRACTIONS: AttractionInfo[] = [
  {
    id: 219,
    nameJa: "ソアリン：ファンタスティック・フライト",
    nameEn: "Soaring: Fantastic Flight",
    area: "ポートディスカバリー",
    areaEn: "Port Discovery",
    heightMin: 102,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "大空を飛ぶ感覚を味わえる人気NO.1アトラクション。身長制限102cm。DPA必須レベルの人気を誇る。",
    descEn: "The most popular attraction at DisneySea — a breathtaking hang-gliding simulation. Height: 102cm+. DPA is highly recommended.",
  },
  {
    id: 255,
    nameJa: "アナとエルサのフローズンジャーニー",
    nameEn: "Anna & Elsa's Frozen Journey",
    area: "ファンタジースプリングス",
    areaEn: "Fantasy Springs",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "「アナと雪の女王」の世界を旅するボートライド。ファンタジースプリングス内で最も人気の高いアトラクション。",
    descEn: "A boat journey through the Frozen kingdom. The most sought-after ride in Fantasy Springs — DPA or early arrival essential.",
  },
  {
    id: 256,
    nameJa: "ラプンツェルのランタンフェスティバル",
    nameEn: "Rapunzel's Lantern Festival",
    area: "ファンタジースプリングス",
    areaEn: "Fantasy Springs",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ランタンが舞う幻想的な世界を巡るボートライド。ラプンツェルの世界観に浸れる新エリアの目玉。",
    descEn: "Drift through a glowing lantern-lit world inspired by Tangled. A Fantasy Springs highlight — DPA makes a big difference here.",
  },
  {
    id: 257,
    nameJa: "ピーター・パンのネバーランドアドベンチャー",
    nameEn: "Peter Pan's Neverland Adventure",
    area: "ファンタジースプリングス",
    areaEn: "Fantasy Springs",
    heightMin: null,
    thrillLevel: 2,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ネバーランドを空から冒険するライド。ファンタジースプリングスの3アトラクション中最もスリリング。",
    descEn: "Soar over Neverland in an adventure ride. The most thrilling of the three Fantasy Springs attractions.",
  },
  {
    id: 243,
    nameJa: "タワー・オブ・テラー",
    nameEn: "Tower of Terror",
    area: "アメリカンウォーターフロント",
    areaEn: "American Waterfront",
    heightMin: 102,
    thrillLevel: 5,
    isDPA: true,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "13階から落下するシー最大のスリルライド。身長制限102cm。心臓の弱い方はご注意を。DPA対象。",
    descEn: "DisneySea's most intense ride — a 13-floor drop tower. Height: 102cm+. Not for the faint of heart. DPA available.",
  },
  {
    id: 222,
    nameJa: "インディ・ジョーンズ・アドベンチャー：クリスタルスカルの魔宮",
    nameEn: "Indiana Jones Adventure: Temple of the Crystal Skull",
    area: "ロストリバーデルタ",
    areaEn: "Lost River Delta",
    heightMin: 117,
    thrillLevel: 4,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "ジープで遺跡を駆け抜けるスリル満点のライド。身長制限117cm。振動が激しいため腰に不安がある方は注意。",
    descEn: "Race through an ancient temple in a jeep. Height: 117cm+. Intense bumps — not ideal if you have back issues.",
  },
  {
    id: 223,
    nameJa: "センター・オブ・ジ・アース",
    nameEn: "Journey to the Center of the Earth",
    area: "ミステリアスアイランド",
    areaEn: "Mysterious Island",
    heightMin: 117,
    thrillLevel: 5,
    isDPA: false,
    bestTime: "morning",
    waitTendency: "high",
    descJa: "地底2万マイルの世界を巡るシー屈指の名作ライド。身長制限117cm。最後の急上昇が圧巻。",
    descEn: "Explore the earth's core in DisneySea's iconic thrill ride. Height: 117cm+. The final launch is unforgettable.",
  },
  {
    id: 218,
    nameJa: "トイ・ストーリー・マニア！",
    nameEn: "Toy Story Mania!",
    area: "アメリカンウォーターフロント",
    areaEn: "American Waterfront",
    heightMin: null,
    thrillLevel: 1,
    isDPA: true,
    bestTime: "afternoon",
    waitTendency: "high",
    descJa: "4Dシューティングゲーム感覚のライド。家族・友人と点数を競おう！DPA対象で待ち時間が長くなりやすい。",
    descEn: "A 4D shooting game ride — compete for the highest score! DPA eligible and popular with families.",
  },
  {
    id: 242,
    nameJa: "レイジングスピリッツ",
    nameEn: "Raging Spirits",
    area: "アラビアンコースト",
    areaEn: "Arabian Coast",
    heightMin: 117,
    thrillLevel: 5,
    isDPA: false,
    bestTime: "evening",
    waitTendency: "medium",
    descJa: "360度ループありの本格コースター。身長制限117cm。夕方に比較的空きやすく狙い目の時間帯。",
    descEn: "A full 360° loop coaster. Height: 117cm+. Waits tend to ease in the evening — worth targeting then.",
  },
  {
    id: 247,
    nameJa: "ニモ＆フレンズ・シーライダー",
    nameEn: "Nemo & Friends SeaRider",
    area: "ポートディスカバリー",
    areaEn: "Port Discovery",
    heightMin: null,
    thrillLevel: 2,
    isDPA: false,
    bestTime: "afternoon",
    waitTendency: "low",
    descJa: "小型潜水艦で海の生き物たちと泳ぐ体験型ライド。待ち時間が少なめで、混雑時の穴場スポット。",
    descEn: "Shrink down and swim with Nemo and friends in a mini sub. One of DisneySea's shorter queues — a smart choice on busy days.",
  },
];
